//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CelebrationOfLife.Library.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.CategoryGalleries = new HashSet<CategoryGallery>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<CategoryGallery> CategoryGalleries { get; set; }
        public virtual CategoryText CategoryText { get; set; }
    }
}
